services:
  postgres:
    image: postgres:15-alpine
    container_name: gateway_db
    environment:
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_pass
      POSTGRES_DB: payment_gateway
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway_user -d payment_gateway"]
      interval: 3s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis_gateway
    ports:
      - "6379:6379"

  api:
    build: ./backend
    container_name: gateway_api
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payment_gateway
      - SPRING_DATASOURCE_USERNAME=gateway_user
      - SPRING_DATASOURCE_PASSWORD=gateway_pass
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: ./backend
    container_name: gateway_worker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payment_gateway
      - SPRING_DATASOURCE_USERNAME=gateway_user
      - SPRING_DATASOURCE_PASSWORD=gateway_pass
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_MAIN_WEB_APPLICATION_TYPE=none
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  dashboard:
    image: nginx:stable-alpine
    container_name: gateway_dashboard
    ports:
      - "3000:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html

  checkout:
    image: nginx:stable-alpine
    container_name: gateway_checkout
    ports:
      - "3001:80"
    volumes:
      - ./checkout:/usr/share/nginx/html
      - ./sdk:/usr/share/nginx/html/sdk